# Generated by Django 3.2.9 on 2021-12-10 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('insertAt', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Create Date')),
                ('updateAt', models.DateTimeField(null=True, verbose_name='Update Date')),
                ('insertUs', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Create')),
                ('updateUs', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Update')),
            ],
        ),
    ]
