# Generated by Django 3.2.9 on 2021-12-10 22:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gyms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mail', models.EmailField(blank=True, max_length=150, unique=True)),
                ('address', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('phone', models.PositiveIntegerField(blank=True, null=True, verbose_name='Phone')),
                ('disabled', models.BooleanField(default=False)),
                ('insertAt', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Create Date')),
                ('updateAt', models.DateTimeField(null=True, verbose_name='Update Date')),
                ('insertUs', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Create')),
                ('updateUs', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Update')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.routes')),
            ],
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('pokemon', models.PositiveIntegerField(blank=True, null=True)),
                ('insertAt', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Create Date')),
                ('updateAt', models.DateTimeField(verbose_name='Update Date')),
                ('insertUs', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Create')),
                ('updateUs', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Update')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('trainerCode', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=30)),
                ('pokedexNumber', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='Experience')),
                ('age', models.DateField(editable=False)),
                ('insertAt', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Create Date')),
                ('updateAt', models.DateTimeField(verbose_name='Update Date')),
                ('insertUs', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Create')),
                ('updateUs', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Update')),
                ('pokeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.poketypes')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=30)),
                ('mail', models.EmailField(blank=True, max_length=150)),
                ('phone', models.PositiveIntegerField(blank=True, unique=True, verbose_name='Phone')),
                ('insertAt', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Create Date')),
                ('updateAt', models.DateTimeField(verbose_name='Update Date')),
                ('insertUs', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Create')),
                ('updateUs', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Update')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserves.gyms')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trainerCode', models.CharField(max_length=30)),
                ('insertAt', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Create Date')),
                ('updateAt', models.DateTimeField(verbose_name='Update Date')),
                ('insertUs', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Create')),
                ('updateUs', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Update')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserves.users')),
            ],
        ),
        migrations.CreateModel(
            name='Reserves',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rentalDateTime', models.DateTimeField(auto_now=True, verbose_name='Rental Date')),
                ('returnDateTime', models.DateTimeField(auto_now=True, verbose_name='Return Date')),
                ('experienceInitial', models.PositiveIntegerField(blank=True, null=True, verbose_name='Experience Initial')),
                ('experienceFinal', models.PositiveIntegerField(blank=True, null=True, verbose_name='Experience Final')),
                ('insertAt', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Create Date')),
                ('updateAt', models.DateTimeField(verbose_name='Update Date')),
                ('insertUs', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Create')),
                ('updateUs', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Update')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserves.observations')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserves.pokemons')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.routes')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.states')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserves.trainers')),
                ('userCreate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserves.users')),
            ],
        ),
    ]
